const express = require("express");
const dotenv = require("dotenv");
dotenv.config({ path: ".env" });
const userRouter = require("./router/userRouter");
const guestRouter = require("./router/guestRouter");
const sustainabilityScoreRouter = require("./router/sustainabilityScoreRouter");
const reportRouter = require("./router/reportRouter");
const app = express();
app.use(express.json());
app.use(process.env.BASE_URL, userRouter);
app.use(process.env.BASE_URL, guestRouter);
app.use(process.env.BASE_URL, sustainabilityScoreRouter);
app.use(process.env.BASE_URL, reportRouter);
module.exports = app;
